spring:
  datasource:
    url: jdbc:${DB_URL}         # 예: postgresql://host:port/dbname (DB_URL에는 "postgresql://..."만 입력)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

aladin:
  api-key: ${ALADIN_API_KEY}
  api-url: http://www.aladin.co.kr/ttb/api/ItemSearch.aspx
