spring:
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


aladin:
  api-key: ${ALADIN_API_KEY}
  api-url: http://www.aladin.co.kr/ttb/api/ItemSearch.aspx
