name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # mvnw 파일에 실행 권한 추가 (중요!)
      - name: Set execute permission for mvnw
        run: chmod +x mvnw

      # Maven으로 빌드 (테스트 생략)
      - name: Maven 빌드
        run: ./mvnw clean package -DskipTests

      # Docker 이미지 빌드
      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/booklog-app:latest .

      # Docker Hub 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 푸시
      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_USERNAME }}/booklog-app:latest
